### ISSUE TITLE
Formatting suggestions

### ISSUE THREAD

**Issue by eugenesvk** [kek91/StatusBarExtended#13]
Just FYI I've made a few edits to the format of the toolbar in a [fork](https://github.com/eugenesvk/StatusBarExtendedF). If you like them, would be happy to send a PR 
(for some reason selection stopped working even with a clean install of your plugin, so can't provide a screenshot of the new format)
![fman-plugin-statusbarextendedf](https://user-images.githubusercontent.com/12956286/29323733-6f61a91c-81ea-11e7-915f-c520db20fc66.png)

### Below is a brief description of the changes
- Shorter size indicators with lower-case for (kilo)bytes: b, k, M, G, T. Kibibyte (2^10) format is preserved
- Change status icon of hidden files toggle to ◻white (hidden files shown) and ◼black (hidden files hidden) Unicode square symbols
- Align all indicator position to keep it the same regardless of the length of the indicator (file/folder count is consistent up to 9,999)
- Remove empty folder/file numbers indicators (including labels) Toolbar only screenshot with a custom theme v0.1.1f 
- Add thousands separator (,) to file/folder numbers (e.g. Files: 1,000)
- Change status of selected items to be consistent with the regular view for faster read

**Comment by kek91** [comment]
That looks fantastic! Yes, please send a PR, I'd be happy to merge it. Thank you :)

**Comment by kek91** [comment]
Merged in #14
