### ISSUE TITLE
Doesn't seem to be working on my end

### ISSUE THREAD

**Issue by oskretc** [kek91/StatusBarExtended#17]
The Status bar only shows 

Pane: Left (square)              Size: 0.0 b

I'm on Win7 

Any way I can help to debug this?

**Comment by kek91** [comment]
Hi oskretc, thanks for reporting the issue.

The plugin actually stopped working a while ago when fman implemented the [new filesystem API](https://fman.io/blog/fmans-new-file-system-api/). I haven't had time to fix the plugin yet even though it shouldn't take long. 

I feel bad about it and now that there's an open issue I guess I got some incentive to finally start working on it... I'll try to get it fixed this week. Will update in a few days... :)
