### ISSUE TITLE
Register as an fman's plugin

### ISSUE THREAD

**Issue by pravic** [kek91/StatusBarExtended#18]
https://fman.io/docs/sharing-plugins

> and add the topics `fman` and `plugin`

**Comment by kek91** [comment]
Thanks for reaching out. Sorry but I deliberately removed the tags because the plugin is outdated and not working in current version of fman. See #17 for more details, haven't had time to fix it yet unfortunately.

**Comment by pravic** [comment]
Well, I've checked the README and the issues list about a possible intention.

Ok, I see.

**Comment by kek91** [comment]
I'll let the issue stay open so you get a notification when the plugin is ready for use again

**Comment by eugenesvk** [comment]
@pravic FYI the plugin has been updated to work with the current fman version and is reregistered
